# fly.toml app configuration file generated for zac-george-gpt on 2023-04-23T19:30:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zac-george-gpt"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[env]
  PINECONE_INDEX_NAME = "zac-george-gpt"